# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffbeb80da7f9576d248eb44414090fcaca37c4c70826597a8acdafa2627000e0b8bb715b9c5ca78ce2536dd4e4bdbab827803e5480586da53f48326754b74086

test:
  secret_key_base: 618d742bea88eb802390e0d19f736f83b4e6c4148e2d614b34e2fd875beb2fb064e81069118716547a6774c420002f172e2009957589083fb7daf8eb9ffb99aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
